### ISSUE TITLE
[dronereceiver]: Add runners/queues info

### ISSUE THREAD

**Issue by Elfo404** [grafana/grafana-ci-otel-collector#21]
Taking inspiration from [Jenkins' exposed metrics](https://github.com/jenkinsci/opentelemetry-plugin/blob/master/docs/monitoring-metrics.md) we should investigate adding metrics about runners / queues.

Drone's SQL DB does not contain these info, which are instead stored in redis, nor it is exposed via APIs. 
~The Receiver should therefore also be able to connect to a redis instance to gather data. 
It is still unknown where/how and if we can get all the info listed~

looks like this info is only kept in memory ant not available. maybe at this stage we cannot implement this

<table>
    <tr>
        <th>Metric</th>
        <th>Unit</th>
        <th>Attribute Key</th>
        <th>Attribute value</th>
        <th>Description</th>
</tr>
<tr>
        <td>jenkins.executor.available</td>
        <td>1</td>
        <td>label</td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>jenkins.executor.busy</td>
        <td>1</td>
        <td>label</td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>jenkins.executor.idle</td>
        <td>1</td>
        <td>label</td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>jenkins.executor.online</td>
        <td>1</td>
        <td>label</td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>jenkins.executor.connecting</td>
        <td>1</td>
        <td>label</td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>jenkins.executor.defined</td>
        <td>1</td>
        <td>label</td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>jenkins.executor.queue</td>
        <td>1</td>
        <td>label</td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>jenkins.queue.waiting</td>
        <td>1</td>
        <td></td>
        <td></td>
        <td>Number of tasks in the queue with the status 'buildable' or 'pending' (see <a href="https://javadoc.jenkins.io/hudson/model/Queue.html#getUnblockedItems--">`Queue#getUnblockedItems()`</a>)</td>
    </tr>
    <tr>
        <td>jenkins.queue.blocked</td>
        <td>1</td>
        <td></td>
        <td></td>
        <td>Number of blocked tasks in the queue. Note that waiting for an executor to be available is not a reason to be counted as blocked. (see <a href="https://javadoc.jenkins.io/hudson/model/queue/QueueListener.html">`QueueListener#onEnterBlocked() - QueueListener#onLeaveBlocked()`</a>)</td>
    </tr>
    <tr>
        <td>jenkins.queue.buildable</td>
        <td>1</td>
        <td></td>
        <td></td>
        <td>Number of tasks in the queue with the status 'buildable' or 'pending' (see <a href="https://javadoc.jenkins.io/hudson/model/Queue.html#getBuildableItems--">`Queue#getBuildableItems()`]</a>)</td>
    </tr>
    <tr>
        <td>jenkins.queue.left</td>
        <td>1</td>
        <td></td>
        <td></td>
        <td>Total count of tasks that have been processed (see [`QueueListener#onLeft`]()-</td>
    </tr>
    <tr>
        <td>jenkins.queue.time_spent_millis</td>
        <td>ms</td>
        <td></td>
        <td></td>
        <td>Total time spent in queue by the tasks that have been processed (see <a href="https://javadoc.jenkins.io/hudson/model/queue/QueueListener.html#onLeft-hudson.model.Queue.LeftItem-">`QueueListener#onLeft()`</a> and <a href="https://javadoc.jenkins.io/hudson/model/Queue.Item.html#getInQueueSince--">`Item#getInQueueSince()`</a>)</td>
    </tr>
    <tr>
        <td>jenkins.disk.usage.bytes</td>
        <td>By</td>
        <td></td>
        <td></td>
        <td>Disk Usage size</td>
    </tr>
</table>

**Comment by dsotirakis** [comment]
not going to work on this actively anymore - closing
